import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local";
import type { Metadata } from "next";
import TopNavigation from "@/components/navigation/top-navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Contentino",
  description: "Your content, generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header>
            <TopNavigation />
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
